### ISSUE TITLE
delete markers?

### ISSUE THREAD

**Issue by infiniteoo** [hlamkins/Project2#20]
obviously we need a way to delete markers from the map, but we should set some restrictions.  

only the user who created the post can delete it?
only a user with a special "admin" account can delete them?

figure out a cool way to make this happen and get it integrated into the project!

**Comment by peterphenow** [comment]
We have a button to delete markers that is working.  Not placed in the greatest spot, but when I move to the infobox, it breaks the functionality.  May look into it more if time permits
