### ISSUE TITLE
what's our team name?  I like: Team HA-PET!

### ISSUE THREAD

**Issue by infiniteoo** [hlamkins/Project2#4]
(heather, adrian, peter, esmond & troy)

**Comment by peterphenow** [comment]
If you like an acronym of our names, I'd suggest PHATE

**Comment by infiniteoo** [comment]
> If you like an acronym of our names, I'd suggest PHATE

brilliant!

**Comment by infiniteoo** [comment]
it's settled.  after group discussion we are now Team PHATE!
