### ISSUE TITLE
hiding our api keys

### ISSUE THREAD

**Issue by infiniteoo** [hlamkins/Project2#6]
i got a very angry letter from google when i pushed my code.  they want us to hide our API keys.  part of the project's requirements is to use environment variables to accomplish this.  please research and figure it out!

**Comment by peterphenow** [comment]
The google maps API key cannot be hidden as it is needed in the HTML to call the source script.  The best we can do is to set restrictions on the API key itself. https://developers.google.com/maps/api-key-best-practices
