### ISSUE TITLE
heroku and jawsDB set up

### ISSUE THREAD

**Issue by infiniteoo** [hlamkins/Project2#9]
Heather, since you're running the project on github, you're being tasked with ensuring the site is up and running on heroku properly, and automatically updates when we push new code to the main brach.

while you're there please ensure the JawsDB integration is properly set up so we can communicate with the database.

please report back, or insert whatever code is needed to make the transition. 

thanks!

**Comment by hlamkins** [comment]
Should be pushing to Heroku
